    export const ENotificationType = {
        OVERDUE_NOTIFICATION_TO_COMPANY: 'OVERDUE_NOTIFICATION_TO_COMPANY',
        OVERDUE_NOTIFICATION_TO_CLIENTS: 'OVERDUE_NOTIFICATION_TO_CLIENTS',
        OVERDUE_FOR_LAST_MONTH_TO_COMPANY: 'OVERDUE_FOR_LAST_MONTH_TO_COMPANY',
      }